sample_survey/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('survey/', include('survey.urls'))
]

survey/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('get_popular_survey/', views.get_popular_survey, name="get_popular_survey"),
    path('get_all_surveys/', views.get_all_surveys, name="get_all_surveys"),
    path('submit_survey/', views.submit_survey, name="submit_survey"),
    path('<str:partial_view>/', views.index, name="index/partial_view"),
    path('<str:partial_view>/<int:pk>', views.index, name="index/partial_view/id"),
]

survey/models.py
from django.db import models
from django.utils import timezone
import datetime


class Survey(models.Model):
    name = models.CharField(max_length=200)
    published_on = models.DateTimeField('Published DateTime')

    def __str__(self):
        return self.name

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.published_on <= now

    was_published_recently.admin_order_field = 'published_on'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Participant(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    participation_datetime = models.DateTimeField('Participation DateTime')

    def __str__(self):
        return "Participant "+str(self.participation_datetime)


class Question(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    created_on = models.DateTimeField('Creation DateTime')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    created_on = models.DateTimeField('Creation DateTime')
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

survey/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse, JsonResponse
from django.template.loader_tags import register
from django.views.decorators.http import require_http_methods
from .models import Survey, Question, Choice, Participant
from django.utils import timezone
from django.core import serializers
import operator

all_partial_views = ['about', 'all_surveys', 'survey_details', 'submit_success']


@require_http_methods(["GET"])
def index(request, partial_view=None, pk=None):
    if partial_view is None:
        partial_view = 'about'
        return render(request, 'survey/index.html', {"partial_view": partial_view, "pk": pk})
    elif all_partial_views.count(partial_view) == 0:
        raise Http404('Partial View not found!')
    elif partial_view == "survey_details" and pk is None:
        raise Http404('Invalid Address! Page Not Found')
    else:
        return render(request, 'survey/index.html', {"partial_view": partial_view, "pk": pk})


@register.inclusion_tag('survey/surveys.html', takes_context=True)
def all_surveys(context):
    surveys = Survey.objects.all()
    return {'surveys': surveys}


@register.inclusion_tag('survey/about.html', takes_context=True)
def about(context):
    return {}


@register.inclusion_tag('survey/survey_details.html', takes_context=True)
def survey_details(context, survey_id):
    survey = Survey.objects.get(id=survey_id)
    return {'survey': survey}


@register.inclusion_tag('survey/submit_success.html', takes_context=True)
def submit_success(context):
    return {}


@require_http_methods(["POST"])
def submit_survey(request):
    form_data = request.POST.copy()
    # Example: {'csrfmiddlewaretoken': ['idT13LGpggg78Yr0rU3vSkT1PQxnM9hT7z97FvuZEBb
    # IU2acygAUr2W3FE9SCGbk'], '1': ['choice/3'], '2': ['choice/5']}
    form_items = list(form_data.items())
    print("form_items", form_items)
    form_items.pop(0)  # the first element is the csrf token. Therefore omit it.
    survey = None
    for item in form_items:
        # Here in 'choice/3', '3' is '<choice_id>'.
        choice_str, choice_id = item
        choice_id = int(choice_id.split('/')[1])
        choice = Choice.objects.get(id=choice_id)
        if survey is None:
            survey = choice.question.survey
        choice.votes = choice.votes + 1
        choice.save()
    if survey is not None:
        participant = Participant(survey=survey, participation_datetime=timezone.now())
        participant.save()
    return redirect('/survey/submit_success/')


@require_http_methods(["GET"])
def get_popular_survey(request):
    popular_survey_id = None
    popular_survey = None
    surveys = Survey.objects.all()
    survey_participants_dict = {}
    for survey in surveys:
        num_participants = Participant.objects.filter(survey=survey).count()
        survey_participants_dict[survey.id] = num_participants
    if len(survey_participants_dict) > 0:
        popular_survey_id = max(survey_participants_dict.items(), key=operator.itemgetter(1))[0]
    if popular_survey_id is not None:
        popular_survey = serializers.serialize("json", surveys.filter(id=popular_survey_id))
    return JsonResponse(popular_survey, safe=False)


@require_http_methods(["GET"])
def get_all_surveys(request):
    surveys = Survey.objects.all()
    questions = Question.objects.all()
    choices = Choice.objects.all()

    return JsonResponse({"surveys": serializers.serialize("json", surveys),
                         "questions": serializers.serialize("json", questions),
                         "choices": serializers.serialize("json", choices)})

survey/templates/survey/about.html
<!-- Background image -->
<div
class="p-5 text-center bg-image"
style="
  background-image: url('https://images.unsplash.com/photo-1543286386-713bdd548da4?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjR8fHN1cnZleXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60');
  height: 400px;
"
>
<div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
  <div class="d-flex justify-content-center align-items-center h-100">
    <div class="text-white">
      <h1 class="mb-3 title-survey-custom">Survey Management   System</h1>
    </div>
  </div>
</div>
</div>

<div class="container mt-4">
  <div class="card" style="background: none;">
    <div class="card-body">
      <h5 class="card-title text-warning">About This App</h5>
      <p class="card-text text-white">This is a survey application created using
        <a href="https://docs.djangoproject.com/en/3.1/intro/tutorial01/" target="_blank">django framework</a>.
        In this app, users can participate in surveys created by the administrator.
        Each survey consists of a short questionnaire. At the same time fun. <br>
        Each participation in the survey is recorded and the admin can track the number of participation for each survey
        and will be notified of the top survey with highest participation. <br>
        Also, can see the stats for each question in a survey with bar chart visualizations rendered using
        <a href="https://www.chartjs.org/" target="_blank">Chartjs</a>.</p>
    </div>
  </div>
</div>

survey/templates/survey/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/survey-app.css' %}">
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>Survey Application</title>
</head>
{% load static %}
<body id="body">
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light" style="background: #000;">
          <div class="container">
            <a class="navbar-brand survey-navbar-link navbar-brand-custom" href="#">Survey  <span class="span-brand-title">System</span></a>
            <button
              class="navbar-toggler"
              type="button"
              data-mdb-toggle="collapse"
              data-mdb-target="#navbarExample01"
              aria-controls="navbarExample01"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarExample01">
                <ul class="navbar-nav mr-auto ml-5">
                    {% if partial_view == "about" %}
                        <li class="nav-item active">
                            <a class="nav-link survey-navbar-link" href="/survey/about/">About <span class="sr-only">(current)</span></a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link survey-navbar-link" href="/survey/about/">About</a>
                        </li>
                    {% endif %}
                    {% if partial_view == "all_surveys" %}
                        <li class="nav-item active">
                            <a class="nav-link survey-navbar-link" href="/survey/all_surveys/">Surveys <span class="sr-only">(current)</span></a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link survey-navbar-link" href="/survey/all_surveys/">Surveys</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                            <a class="nav-link survey-navbar-link" href="/admin/">Admin Page</a>
                    </li>
                </ul>
            </div>
          </div>
        </nav>
        <!-- Navbar -->
      
        
        <!-- Background image -->
      </header>
        {% if partial_view == 'about' %}
            {% about %}
        {% endif %}
        {% if partial_view == 'all_surveys' %}
            {% all_surveys %}
        {% endif %}
        {% if partial_view == 'survey_details' %}
            {% survey_details pk %}
        {% endif %}
        {% if partial_view == 'submit_success' %}
            {% submit_success %}
        {% endif %}

</body>
</html>

survey/templates/survey/submit_success.html
<div class="container" style="width: 50%; margin:auto;">
  <div class="card" style="background: none;">
    {% load static %}
    <div class="card-body">
      <p class="card-text text-white">Thank you for taking part in the survey. We whole heartedly appreciate it.</p>
      <a href="/survey/all_surveys" class="btn btn-primary">Take Another Survey</a>
    </div>
  </div>
</div>

survey/templates/survey/survey_details.html
<div class="container">
  <div class="card survey-form-card mt-3">
    <div class="card-body">
        <h2 style="color: #000;">{{survey.name}} Survey</h2>
        <p class="card-text">Hello! <br> <br>
          Kindly fill in the survey and submit to participate <br>
          If you have any concerns, please do not hesitate to reach out to us via email or phone <br>
          alexotieno900@gmail.com <br>
          (+254779663469) <br>
        </p>
        <form action="/survey/submit_survey/" method="post">
        {% csrf_token %}
        {% for question in survey.question_set.all %}
            <fieldset class="form-group">
                <legend class="col-form-label col-form-label-custom col-md-12 pt-0">{{question.id}}. {{question.question_text}}</legend>
                <div class="col-md-12">
                  {% for choice in question.choice_set.all %}
                      <div class="form-check form-check-custom">
                        <input class="form-check-input" type="radio" name="{{question.id}}"
                               id="{{question.id}}{{choice.id}}" value="choice/{{choice.id}}" aria-describedby="radioHelp">
                        <label class="form-check-label" for="{{question.id}}{{choice.id}}">
                          {{choice.choice_text}}
                        </label>
                      </div>
                  {% endfor %}
                  <small id="radioHelp" class="form-text form-text-custom text-muted">Please select one of the available choices.</small>
                </div>
            </fieldset>
            <hr/>
        {% endfor %}
        <div class="form-group row">
          <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

survey/templates/survey/surveys.html
<div class="container">
  
<div class="card mt-4" style="background: none;">
  <h5 class="card-header text-white">Available Surveys</h5>
  <div class="card-body">
      <p class="card-text text-white">Participate in as many surveys as you like and help us understand you better!</p>
      <ul>
        {% for survey in surveys %}
            <li class="mt-4">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">
                      <a href="/survey/survey_details/{{survey.id}}">{{survey.name}}</a>
                    </h5>
                  </div>
                </div>
            </li>
        {% endfor %}
      </ul>
  </div>
</div>
</div>